server:
  port: 9527
  
spring:
  application:
    name: springcloud-zuul-gateeay
    
eureka:
  client:
    service-url:
      defaultZone: http//eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003:7003/eureka
    instance: 
      instance-id: gateway-9527.com
      prefer-ip-address: true

zuul:
  prefix: /atguigu
  #ignored-services: springcloud-dept
  ignored-services: "*"
  routes: 
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**  
  
      
info: 
  app.name: atguigu-springcloud
  company.name: www.atguigu.com
  build.artifactId: springcloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT
   
